### PR TITLE
make login and spreate the handler file into files

### PR DESCRIPTION
**Pull request by Hadeel-Salamin**
separate each error in a function
separate the big functions to new files to make it more clear
edited the home handler function to go to the login page/user profile

### CODE REVIEW

**Comment by m4v15** [comment]
Hey 👋 

I really like the idea of seperating out the handlers, nice work.

However, if you are going to do it, **plan it out carefully**

At the moment your handlers are all in different places and it makes the code messy and hard to read.

See #37 but I recommend the following structure:
```
-src/
--queries/
--server/
----server.js
----router.js
----handler/
------ home.js //home handler
------ login.js // login handler
------ public.js
------ signup.js
etc
```

Sure maybe some of the more simple ones can be in one file, but I would recommend to do something like the above to make you file structure **significantly** better

**Review by m4v15 — CHANGES_REQUESTED** [review]
see comment

**Review by Samaamro20 — APPROVED** [review]
OK

**Comment by Samaamro20** [comment]
@m4v15  maybe if we have a time to the project , we will make it .

**Review by jema28 — APPROVED** [review]
Please keep in mind what Matt said about planning as it was quite hard/review to read this PR! The login works so going to merge ❤️

**Pull request merged**
